# Generated by Django 2.1.7 on 2019-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, db_column='Categoria', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Catalogo',
            },
        ),
        migrations.CreateModel(
            name='Presentacion1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(blank=True, db_column='Presentacion', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Presentacion_1',
            },
        ),
        migrations.CreateModel(
            name='Unidadmedida1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medida', models.CharField(blank=True, db_column='Medida', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'UnidadMedida_1',
            },
        ),
    ]
