# Generated by Django 2.1.7 on 2019-02-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrec', models.CharField(blank=True, db_column='NombreC', max_length=45, null=True)),
                ('apellido', models.CharField(blank=True, db_column='Apellido', max_length=45, null=True)),
                ('nit', models.CharField(blank=True, db_column='Nit', max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=200, null=True)),
                ('numero', models.IntegerField(blank=True, db_column='Numero', null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=45, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'Cliente',
            },
        ),
    ]
