# Generated by Django 2.1.7 on 2019-02-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facturaventa',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, db_column='Total', decimal_places=2, max_digits=10, null=True)),
                ('fecha', models.DateTimeField(blank=True, db_column='Fecha', null=True)),
                ('serie', models.CharField(blank=True, db_column='Serie', max_length=45, null=True)),
                ('numero', models.CharField(blank=True, db_column='Numero', max_length=45, null=True)),
                ('cantidad_prod', models.IntegerField(blank=True, db_column='Cantidad_Prod', null=True)),
                ('anulado', models.IntegerField(blank=True, db_column='Anulado', null=True)),
                ('trans', models.DateTimeField(blank=True, db_column='Trans', null=True)),
                ('fechaanulado', models.DateTimeField(blank=True, db_column='FechaAnulado', null=True)),
                ('subtotal', models.DecimalField(blank=True, db_column='SubTotal', decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, db_column='Descuento', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'FacturaVenta',
                'managed': False,
            },
        ),
    ]
