# Generated by Django 2.1.7 on 2019-03-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=45, null=True)),
                ('existencia', models.IntegerField(blank=True, db_column='Existencia', default=0, null=True)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=45, null=True)),
                ('codigo', models.CharField(blank=True, db_column='Codigo', max_length=45, null=True, unique=True)),
                ('stockminimo', models.IntegerField(blank=True, db_column='StockMinimo', null=True)),
                ('ganancia', models.DecimalField(blank=True, db_column='Ganancia', decimal_places=2, max_digits=10, null=True)),
                ('imagen', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Producto',
                'managed': False,
            },
        ),
    ]
